from typing import Protocol
import numpy as np

class IVADEngine(Protocol):
    def is_speech(self, audio_chunk: np.ndarray) -> bool:
        ...

class IDeviceProvider(Protocol):
    """Abstracts AudioCaptureManager"""
    def get_default_microphone(self) -> int: ...
    def get_system_loopback(self) -> int | None: ...
    def open_stream(self, device_index: int, sample_rate: int, 
                    chunk_size: int, is_loopback: bool = False): ...
    def terminate(self) -> None: ...